export const astorItemsWithFRT = [
  { description: "PDI Inspection", frt: 0.5 },
  { description: "PRE-PDI Inspection", frt: 0.1 },
  { description: "ASTOR 20K Periodic Maintenance", frt: 1.0 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { description: "3M AC Evaporator Cleaning", frt: 1.5 },
  { description: "Complete Car washing and Cleaning", frt: 1.0 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 2.0 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { description: "Mirror - exterior - left - renew", frt: 0.3 },
  { description: "TMPS calibration", frt: 0.4 },
  { description: "Sublet MISC", frt: 1.0 },
  { description: "ASTOR 30K Periodic Maintenance", frt: 1.0 },
  { description: "Brake cleaning -4 wheels", frt: 1.0 },
  { description: "DIY Accessory", frt: 0.1 },
  { description: "ASTOR 40K Periodic Maintenance", frt: 1.0 },
  { description: "Molding assembly - rear wheel - left - renew", frt: 0.2 },
  { description: "3rd Free Service/10,000 KM Service EV", frt: 0.5 },
  { description: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { description: "Brake fluid - renew", frt: 0.8 },
  { description: "3M MG Exterior Beautification", frt: 2.5 },
  { description: "3M MG Engine Compartment Clean", frt: 0.5 },
  { description: "3M Rodent Repellent", frt: 0.5 },
  { description: "Blower Motor cleaning", frt: 0.5 },
  { description: "Brake pads - front - set - renew", frt: 0.7 },
  { description: "Pickup and Drop 1", frt: 0.5 },
  { description: "Replace/Remove and refit Front brake pad", frt: 0.7 },
  { description: "First Free Service/1000 KM Checkup", frt: 0.5 },
  { description: "CLUTCH BLEEDING", frt: 1.0 },
  { description: "Clutch pressure plate - renew", frt: 3.0 },
  { description: "Second Free Service/5000 KM Checkup - EV", frt: 0.5 },
  { description: "3M MG Surface Protection - UV Treatment", frt: 0.5 },
  { description: "3M Silencer Coating", frt: 0.5 },
  { description: "3M AC Vent Disinfectant", frt: 0.5 },
  { description: "ASTOR 70K Periodic Maintenance", frt: 1.0 },
  { description: "Sublet 4", frt: 0.4 },
  { description: "Head Light Lh Replacement", frt: 0.7 },
  { description: "Sublet 6", frt: 0.5 },
  { description: "Tail Lamp Lh Replacement", frt: 0.34 },
  { description: "Arms - windscreen wiper - front - both - renew", frt: 0.2 },
  { description: "Blade - windscreen wiper - passenger - renew", frt: 0.2 },
  { description: "DIY Accessory Fitment", frt: 0.3 },
  { description: "ASTOR 50K Periodic Maintenance", frt: 1.0 },
  { description: "Only Pick (> 20Kms)", frt: 0.1 },
  { description: "Wheel Alignment Measurement and Adjustment", frt: 1.0 },
  { description: "Blades - windscreen wiper - front - both", frt: 0.2 },
  { description: "Sublet 6", frt: 1.0 },
  { description: "Valves - brake bleeder - front - both - renew", frt: 1.0 },
  { description: "Sublet 3", frt: 1.0 },
  { description: "Accessory Fitment", frt: 1.0 },
  { description: "Battery Replacement -Vehicle", frt: 0.2 },
  { description: "Headlamp assemblies - both - renew", frt: 0.8 },
  { description: "Sublet 5", frt: 0.5 },
  { description: "One side Pickup or drop 3", frt: 1.5 },
  { description: "Sublet 2", frt: 1.0 },
  { description: "Tyre pressure sensors - set - renew", frt: 1.8 },
  { description: "Sublet 3", frt: 0.3 },
  { description: "Wuerth MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { description: "Sublet 4", frt: 1.0 },
];



export const cometItemsWithFRT = [
  { description: "PDI Inspection", frt: 0.1 },
  { description: "PRI PDI INSPCTION", frt: 0.1 },
  { description: "Third Free Service/10000 KM Comet", frt: 0.5 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { description: "3M AC Evaporator Cleaning", frt: 1.0 },
  { description: "Steering wheel control switch Inspection", frt: 0.1 },
  { description: "Vehicle General Checkup No Issue found", frt: 0.1 },
  { description: "Paid Service/COMETPMS20000 KM COMET", frt: 1.0 },
  { description: "Complete Car washing and Cleaning", frt: 1.0 },
  { description: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { description: "Left And Right Front Brake Pads Replacem", frt: 0.6 },
  { description: "First Free Service/1000 KM Comet", frt: 0.5 },
  { description: "Sublet MISC", frt: 1.0 },
  { description: "Second Free Service/5000 KM Comet", frt: 0.5 },
  { description: "Paid Service/COMETPMS30000 KM COMET", frt: 1.0 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 1.0 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 1.0 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "3M MG Exterior Beautification", frt: 1.0 },
  { description: "Sublet 5", frt: 0.5 },
  { description: "Sublet 1", frt: 0.2 },
  { description: "Sublet 6", frt: 0.5 },
  { description: "One side Pickup or drop 2", frt: 1.0 },
  { description: "Paid Service/COMETPMS40000 KM COMET", frt: 1.0 }
];

export const glosterItemsWithFRT = [
  { description: "BCM Configuration update for coolant lev", frt: 0.3 },
  { description: "Caliper Carrier Bolt Torque Verification", frt: 0.3 },
  { description: "Sunroof Inspection and adjustment", frt: 0.5 },
  { description: "Front and Rear Camera rework", frt: 0.5 },
  { description: "First Free Service/1000 KM Check up", frt: 1.0 },
  { description: "Console Water Deflector Pasting", frt: 0.9 },
  { description: "Sublet MISC", frt: 1.0 },
  { description: "AC Filter replacement/Clean", frt: 0.3 },
  { description: "Brake oil Replacement", frt: 1.0 },
  { description: "SECTION-FRT BRK FAC", frt: 0.6 },
  { description: "Blower Motor cleaning", frt: 0.5 },
  { description: "Paid Service/105000 KM Diesel", frt: 1.0 },
  { description: "Battery Replacement -Vehicle", frt: 0.2 },
  { description: "Vehicle General Checkup No Issue found", frt: 0.1 },
  { description: "Tyres Replacement - Two Wheels", frt: 0.6 },
  { description: "Protective tape application", frt: 1.7 },
  { description: "Paid Service/60000 KM Diesel", frt: 1.0 },
  { description: "3M Silencer Coating", frt: 0.5 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { description: "3M MG Exterior Beautification", frt: 2.5 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "Complete Car washing and Cleaning", frt: 1.0 },
  { description: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { description: "Pre PDI Inspection", frt: 1.0 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { description: "Paid Service/120000 KM Diesel", frt: 1.0 },
  { description: "CAMERA-FRONT", frt: 0.2 },
  { description: "PDI Inspection", frt: 1.0 },
  { description: "Sublet 6", frt: 0.5 },
  { description: "Paid Service/30000 KM Diesel", frt: 1.0 },
  { description: "Condensor replace, AC filter clean/repla", frt: 1.0 },
  { description: "Ac Gas Refilling", frt: 0.8 },
  { description: "Sublet 6", frt: 1.0 },
  { description: "PACKAGE-LINING REPAIR", frt: 0.5 },
  { description: "Sublet 5", frt: 0.5 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 2.0 },
  { description: "Sublet 3", frt: 0.3 },
  { description: "Paid Service/45000 KM Diesel", frt: 1.0 },
  { description: "3M Rodent Repellent", frt: 0.5 },
  { description: "IDLER PULLEY-TMG", frt: 1.5 },
  { description: "IDLER PULLEY GATES-ACSRY BLT", frt: 0.7 },
  { description: "Engine Coolant Tank Batch Code inspectio", frt: 0.1 },
  { description: "Third Free Service/15,000 KM Service", frt: 1.0 },
  { description: "GENERATOR ASM", frt: 1.4 }
];

export const hectorItemswithFRT = [
  { description: "PDI Inspection", frt: 0.5 },
  { description: "Sublet MISC", frt: 1 },
  { description: "5th Free Service/30,000 KM Service Gasol", frt: 0.5 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { description: "TMPS calibration", frt: 0.4 },
  { description: "Complete Car washing and Cleaning", frt: 1 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 2 },
  { description: "Paid Service/40000 KM Petrol", frt: 1 },
  { description: "3M Anti-Microbial Smoggy", frt: 1 },
  { description: "3M MG Engine Compartment Clean", frt: 0.5 },
  { description: "Brake bleeding", frt: 0.7 },
  { description: "Second Free Service/5000 KM Checkup - Ga", frt: 0.5 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "Paid Service/60000 KM Petrol", frt: 1 },
  { description: "3M AC Evaporator Cleaning", frt: 1.5 },
  { description: "Paid Service/105000 KM Diesel", frt: 1 },
  { description: "3M Silencer Coating", frt: 0.5 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { description: "3M Rodent Repellent", frt: 0.5 },
  { description: "clutch release bearing replacemnt", frt: 4.5 },
  { description: "Paid Service/120000 KM Petrol", frt: 1 },
  { description: "DUCT-FLR FRT AIR OTLT", frt: 0.1 },
  { description: "5th Free Service/45,000 KM Service-Diese", frt: 0.5 },
  { description: "3M MG Exterior Beautification", frt: 2.5 },
  { description: "Paid Service/90000 KM Petrol", frt: 1 },
  { description: "Paid Service/90000 KM Diesel", frt: 1 },
  { description: "Paid Service/20000 KM Petrol", frt: 1 },
  { description: "Wheel Alignment Measurement and Adjustme", frt: 1 },
  { description: "Sublet 2", frt: 0.3 },
  { description: "3M AC Vent Disinfectant", frt: 0.5 },
  { description: "Replace compressor belt idler", frt: 0.4 },
  { description: "Tyres Replacement - Four Wheels", frt: 1.2 },
  { description: "Timing Chain Tensioner Assembly Replacem", frt: 2.4 },
  { description: "Timing Chain Replacement", frt: 1.5 },
  { description: "TENSIONER ASM-DRV BELT Replacement", frt: 0.3 },
  { description: "TENSIONER ASM-DRV BELT Replacemnt", frt: 1.5 },
  { description: "Front Brake Pad Replacement", frt: 0.6 },
  { description: "Rear Brake Pad Replacement", frt: 0.6 },
  { description: "Sublet 6", frt: 0.5 },
  { description: "Second Free Service/7500 KM Checkup - Di", frt: 0.5 },
  { description: "Paid Service/100000 KM Petrol", frt: 1 },
  { description: "Replacement Steering Gear Assembly - Ele", frt: 1.1 },
  { description: "Right Tie Rod  Replacement", frt: 0.3 },
  { description: "Replace battery base", frt: 0.3 },
  { description: "Paid Service/135000 KM Diesel", frt: 1 },
  { description: "Vehicle General Checkup No Issue found", frt: 0.1 },
  { description: "Tyres Replacement - One Wheel", frt: 0.3 },
  { description: "4th Free Service/30,000 KM Service-Diese", frt: 0.5 },
  { description: "DIY Accessory", frt: 0.1 },
  { description: "Left Rear Side Door Window Glass Lift  R", frt: 0.4 },
  { description: "Inspection of PUMA Bolt", frt: 0.3 },
  { description: "Replacing the left Rear door glass regul", frt: 0.5 },
  { description: "Blower Motor cleaning", frt: 0.5 },
  { description: "Paid Service/50000 KM Petrol", frt: 1 },
  { description: "Radiator Fan Replacement", frt: 0.5 },
  { description: "Ac Gas Refilling", frt: 0.8 },
  { description: "4th Free Service/20,000 KM Service Gasol", frt: 0.5 },
  { description: "Sublet 5", frt: 0.5 },
  { description: "Pre PDI Inspection", frt: 0.5 },
  { description: "Paid Service/75000 KM Diesel", frt: 1 },
  { description: "Engine Oil  Pressure Switch Replacement", frt: 0.3 },
  { description: "Paid Service/60000 KM Diesel", frt: 1 },
  { description: "3rd Free Service/10,000 KM Service Gasol", frt: 0.5 },
  { description: "BLADE KIT-WSW Replacemnt", frt: 0.2 },
  { description: "DEFLECTOR-FRT AIR<USE 13C 5800A> Replace", frt: 0.1 },
  { description: "Rear wiper Blade replacement", frt: 0.1 },
  { description: "Sublet 1", frt: 0.2 },
  { description: "Replacing the front wiper assembly", frt: 0.1 },
  { description: "Paid Service/110000 KM Petrol", frt: 1 },
  { description: "DIY Accessory Fitment", frt: 0.3 },
  { description: "3M Underbody Anti-Rust Coating", frt: 1 },
  { description: "Replace the horn assembly", frt: 0.3 },
  { description: "Paid Service/120000 KM Diesel", frt: 1 },
  { description: "Top Left Handle Replacement", frt: 0.1 },
  { description: "MGerm Shield - Anti Microbial Sanitizati", frt: 1 },
  { description: "GENERATOR ASM Replacement", frt: 0.6 },
  { description: "Tyres Replacement - Two Wheels", frt: 0.6 },
  { description: "MODULE ASM-COMN INTERFACE (W/REGULATORY", frt: 1 },
  { description: "First Free Service/1000 KM Checkup - Die", frt: 0.5 },
  { description: "ACCESSORIES PART SUPPORT", frt: 1 },
  { description: "Battery  Replacement", frt: 0.2 },
  { description: "Replacing the rear fog lamp assembly", frt: 0.7 },
  { description: "Replace right front shock absorber/coil", frt: 1 },
  { description: "Replacing Hood Struts and/or Bushings/St", frt: 0.1 },
  { description: "Replacing the right rear coil spring or/", frt: 0.3 },
  { description: "Replacing the left exterior rearview mir", frt: 0.3 },
  { description: "Replace left front door harness assembly", frt: 0.5 },
  { description: "Right Rear Door Glass Replacement", frt: 0.3 },
  { description: "Replace compressor assembly", frt: 0.9 },
  { description: "Crankshaft Oil Seal Replacement", frt: 2.8 },
  { description: "Condenser  Replacement", frt: 1.5 },
  { description: "Evaporator Assy. Replacemnt", frt: 0.6 },
  { description: "One side Pickup or drop 2", frt: 1 },
  { description: "First Free Service/1000 KM Checkup", frt: 0.5 },
  { description: "3M MG Special Combo 1 - Exterior Beautif", frt: 4 },
  { description: "DUCT KIT-FRT INT AIR Replacement", frt: 0.1 },
  { description: "Paid Service/150000 KM Diesel", frt: 1 },
  { description: "HORN ASM-GENERIC (LOW TONE)", frt: 0.3 },
  { description: "CLUTCH BLEEDING", frt: 1 },
  { description: "Replacing the Right Rear door glass regu", frt: 0.5 },
  { description: "DIY Accessory", frt: 1 },
  { description: "AC Gas refill, AC filter clean/replace,", frt: 1 },
  { description: "Starter Motor Assembly Replacement", frt: 0.4 },
  { description: "Replace air conditioner compressor/water", frt: 0.4 },
  { description: "Replace/Remove and refit Timing belt", frt: 2.4 },
  { description: "MODULEASM-GLOWPLUGCONT Replacement", frt: 0.4 },
  { description: "Sublet 4", frt: 0.4 },
  { description: "DISCOUNT ON INVOICE", frt: 1 },
  { description: "Courtesy Car", frt: 1 },
  { description: "Sublet 3", frt: 0.3 },
  { description: "Transmission Oil Replacement", frt: 0.5 },
  { description: "Clutch Bleeding", frt: 0.7 },
  { description: "Right Front Brake Disc Replacement", frt: 0.4 },
  { description: "Left Steering Knuckle  Replacement", frt: 0.7 },
  { description: "Right Steering Knuckle  Replacement", frt: 0.7 },
  { description: "Paid Service/80000 KM Petrol", frt: 1 },
  { description: "Replace steering column intermediate sha", frt: 0.4 },
  { description: "One side Pickup or drop 3", frt: 1.5 },
  { description: "Replacing the left front foot air duct", frt: 0.3 },
  { description: "Intake Manifold Assembly Replacement", frt: 1 },
  { description: "replace intercooler", frt: 1.1 },
  { description: "PIPE ASM-TURBO COOL RETURN Replacement", frt: 0.3 },
  { description: "PIPE ASM-EXH Replacement", frt: 0.2 },
  { description: "3rd Free Service/15,000 KM Service - Die", frt: 0.5 },
  { description: "Right Front Shock Absorber Dust Cover Re", frt: 1 },
  { description: "Transmission Oil Replacement - AT", frt: 0.5 },
  { description: "Replacing the electric glass regulator a", frt: 0.5 },
  { description: "Left Front Lower Control Arm  Replacemen", frt: 0.4 },
  { description: "Front RightLower Control Arm Assembly Re", frt: 0.4 },
  { description: "Left Tie Rod  Replacement", frt: 0.3 },
  { description: "Left Stabilizer Bar Link Replacement", frt: 0.4 },
  { description: "Right Stabilizer Link Replacement", frt: 0.4 },
  { description: "Paid Service/30000 KM Diesel", frt: 1 },
  { description: "AC GAS FLUSHING/FILLING", frt: 1 },
  { description: "SEAL-W/PMP (O RING) Replacement", frt: 1.1 },
  { description: "Left Engine Mount Replacement", frt: 0.6 },
  { description: "Radiator Left Mounting Bracket Replaceme", frt: 0.2 },
  { description: "Replacing the upper mounting plate trim", frt: 0.3 },
  { description: "RECEPTACLE ASM-USB Replacement", frt: 0.2 },
  { description: "Harness Replacemnt", frt: 3.2 },
  { description: "Paid Service/70000 KM Petrol", frt: 1 },
  { description: "Replacing the rear window wiper motor", frt: 0.3 },
  { description: "A Wheel Replacement", frt: 0.3 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 1 },
  { description: "Sublet 6", frt: 1 },
  { description: "Paid Service/210000 KM Diesel", frt: 1 },
  { description: "Sublet 3", frt: 1 },
  { description: "Sublet 2", frt: 1 },
  { description: "MOLDING ASM-FRT S/D LWR Replacement", frt: 0.1 },
  { description: "Sublet 5", frt: 1 },
  { description: "Remove and refit Left complete rear view", frt: 0.2 },
  { description: "Sublet 4", frt: 1 },
  { description: "Driver Airbag Clock Spring Replacement", frt: 0.4 },
  { description: "3M MG Exterior Beautification", frt: 1 },
  { description: "Sublet 1", frt: 1 },
  { description: "Right Rear Brake Disc  Replacement", frt: 0.6 },
  { description: "Replace/Remove and refit Right rear wind", frt: 0.3 },
  { description: "Fog lamp LH Replacement", frt: 0.59 },
  { description: "Generator Mounting Bracket Replacement", frt: 0.6 },
  { description: "Replacing the left front/Rear door glass", frt: 0.5 },
  { description: "Replacement Radiator Fan", frt: 0.5 },
  { description: "Pick and Drop > 20Kms", frt: 0.1 },
  { description: "3M AC Evaporator Cleaning", frt: 1 },
  { description: "Coolant Replacement", frt: 0.5 },
  { description: "Replace the relief valve", frt: 0.5 },
  { description: "Wheels Carry Out Stationary Balancing -", frt: 0.8 },
  { description: "RETAINER-A/TRNS FLEX PLT Replacement", frt: 2.7 },
  { description: "Engine overhaul", frt: 10 },
];

export const windosrItemsWithFrt = [
  { description: "PDI Inspection", frt: 0.5 },
  { description: "PRE PDI Inspection", frt: 0.1 },
  { description: "Sublet MISC", frt: 1.0 },
  { description: "3M MG Exterior Beautification", frt: 1.0 },
  { description: "Complete Car washing and Cleaning", frt: 1.0 },
  { description: "Second Free Service/5000 KM WINDSOR", frt: 1.0 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 1.0 },
  { description: "First Free Service/1000 KM WINDSOR", frt: 1.0 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 1.0 },
  { description: "Accessory Mats Fitment", frt: 0.2 },
  { description: "Accessory Fitment", frt: 1.0 },
  { description: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { description: "Windsor Software Update", frt: 0.3 },
  { description: "Wheel alignment - check and adjust", frt: 0.7 },
  { description: "3M AC Evaporator Cleaning", frt: 1.0 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 }
];

export const ZSItemsWithFrt = [
  { description: "PDI Inspection", frt: 0.1 },
  { description: "PRI PDI INSPCTION", frt: 0.1 },
  { description: "Blower motor connector pigtail replaceme", frt: 0.3 },
  { description: "Sublet MISC", frt: 1.0 },
  { description: "HV Battery Breather Valve & Cap fitment", frt: 0.5 },
  { description: "Paid Service/50000 KM EV", frt: 1.0 },
  { description: "Complete Car washing and Cleaning", frt: 1.0 },
  { description: "3M AC Vent Disinfectant", frt: 0.5 },
  { description: "3rd Free Service/10,000 KM Service EV", frt: 0.5 },
  { description: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { description: "TMPS calibration", frt: 0.4 },
  { description: "Pickup and Drop 3", frt: 1.5 },
  { description: "3M MG Premium Interior Cleaning (Foam)", frt: 2.0 },
  { description: "Paid Service/60000 KM EV", frt: 1.0 },
  { description: "Vehicle General Checkup No Issue found", frt: 0.1 },
  { description: "Paid Service/20000 KM EV", frt: 1.0 },
  { description: "3M AC Evaporator Cleaning", frt: 1.5 },
  { description: "3M MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { description: "Sublet 1", frt: 0.2 },
  { description: "4th Free Service/20,000 KM Service EV", frt: 0.5 },
  { description: "3M Rodent Repellent", frt: 0.5 },
  { description: "Blower Motor cleaning", frt: 0.5 },
  { description: "Brake cleaning -4 wheels", frt: 1.0 },
  { description: "3M MG Exterior Beautification", frt: 2.5 },
  { description: "Paid Service/140000 KM EV", frt: 1.0 },
  { description: "Paid Service/40000 KM EV", frt: 1.0 },
  { description: "Paid Service/90000 KM EV", frt: 1.0 },
  { description: "DIY Accessory", frt: 0.1 },
  { description: "Sublet 6", frt: 0.5 },
  { description: "5th Free Service/30,000 KM Service EV", frt: 0.5 },
  { description: "Second Free Service/5000 KM Checkup - EV", frt: 0.5 },
  { description: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { description: "3M MG Engine Compartment Clean", frt: 0.5 },
  { description: "Paid Service/30000 KM EV", frt: 1.0 },
  { description: "3M MG Special Combo 1 - Exterior Beautif", frt: 4.0 },
  { description: "Horns - both - renew", frt: 0.3 },
  { description: "Blower assembly - renew", frt: 0.3 },
  { description: "Coolant - battery - renew", frt: 0.5 },
  { description: "Bulb replacement -1", frt: 0.2 },
  { description: "First Free Service/1000 KM Checkup", frt: 0.5 },
  { description: "Paid Service/110000 KM EV", frt: 1.0 },
  { description: "Paid Service/130000 KM EV", frt: 1.0 },
  { description: "Brake oil Top Up", frt: 0.3 },
  { description: "Paid Service/80000 KM EV", frt: 1.0 },
  { description: "Paid Service/120000 KM EV", frt: 1.0 },
  { description: "Transmission Oil Replacement", frt: 0.5 },
  { description: "Coolant Replacement", frt: 0.5 },
  { description: "Battery Replacement -Vehicle", frt: 0.2 },
  { description: "Paid Service/70000 KM EV", frt: 1.0 },
  { description: "One side Pickup or drop 1", frt: 0.5 },
  { description: "Head Light Lh Replacement", frt: 1.19 },
  { description: "3M GermKleen", frt: 1.0 },
  { description: "Blades - windscreen wiper - front - both", frt: 0.2 },
  { description: "Head Light Rh Replacement", frt: 1.19 },
  { description: "Replace Brake fluid", frt: 0.6 },
  { description: "Buckle - seat belt - 2nd - left - renew", frt: 0.3 },
  { description: "Battery - renew", frt: 0.4 },
  { description: "Only Drop (> 20Kms)", frt: 0.1 },
  { description: "Combined charging unit - renew", frt: 0.6 },
  { description: "Replace/Remove and refit Steering contro", frt: 0.2 },
  { description: "Sublet 3", frt: 0.3 },
  { description: "Air conditioning compressor - renew", frt: 1.4 },
  { description: "Cushion assembly - driver seat - renew", frt: 0.8 }
];
