const astorItemsWithFrt = [
  { name: "PDI Inspection", frt: 0.5 },
  { name: "PRE-PDI Inspection", frt: 0.1 },
  { name: "ASTOR 20K Periodic Maintenance", frt: 1.0 },
  { name: "Wheel Alignment and Balancing ( 4 Tyres)", frt: 1.5 },
  { name: "3M AC Evaporator Cleaning", frt: 1.5 },
  { name: "Complete Car washing and Cleaning", frt: 1.0 },
  { name: "Pickup and Drop 3", frt: 1.5 },
  { name: "3M MG Premium Interior Cleaning (Foam)", frt: 2.0 },
  { name: "3M MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { name: "Mirror - exterior - left - renew", frt: 0.3 },
  { name: "TMPS calibration", frt: 0.4 },
  { name: "Sublet MISC", frt: 1.0 },
  { name: "ASTOR 30K Periodic Maintenance", frt: 1.0 },
  { name: "Brake cleaning -4 wheels", frt: 1.0 },
  { name: "DIY Accessory", frt: 0.1 },
  { name: "ASTOR 40K Periodic Maintenance", frt: 1.0 },
  { name: "Molding assembly - rear wheel - left - renew", frt: 0.2 },
  { name: "3rd Free Service/10,000 KM Service EV", frt: 0.5 },
  { name: "3M Anti-Microbial Smoggy", frt: 1.0 },
  { name: "Brake fluid - renew", frt: 0.8 },
  { name: "3M MG Exterior Beautification", frt: 2.5 },
  { name: "3M MG Engine Compartment Clean", frt: 0.5 },
  { name: "3M Rodent Repellent", frt: 0.5 },
  { name: "Blower Motor cleaning", frt: 0.5 },
  { name: "Brake pads - front - set - renew", frt: 0.7 },
  { name: "Pickup and Drop 1", frt: 0.5 },
  { name: "Replace/Remove and refit Front brake pad", frt: 0.7 },
  { name: "First Free Service/1000 KM Checkup", frt: 0.5 },
  { name: "CLUTCH BLEEDING", frt: 1.0 },
  { name: "Clutch pressure plate - renew", frt: 3.0 },
  { name: "Second Free Service/5000 KM Checkup - EV", frt: 0.5 },
  { name: "3M MG Surface Protection - UV Treatment", frt: 0.5 },
  { name: "3M Silencer Coating", frt: 0.5 },
  { name: "3M AC Vent Disinfectant", frt: 0.5 },
  { name: "ASTOR 70K Periodic Maintenance", frt: 1.0 },
  { name: "Sublet 4", frt: 0.4 },
  { name: "Head Light Lh Replacement", frt: 0.7 },
  { name: "Sublet 6", frt: 0.5 },
  { name: "Tail Lamp Lh Replacement", frt: 0.34 },
  { name: "Arms - windscreen wiper - front - both - renew", frt: 0.2 },
  { name: "Blade - windscreen wiper - passenger - renew", frt: 0.2 },
  { name: "DIY Accessory Fitment", frt: 0.3 },
  { name: "ASTOR 50K Periodic Maintenance", frt: 1.0 },
  { name: "Only Pick (> 20Kms)", frt: 0.1 },
  { name: "Wheel Alignment Measurement and Adjustment", frt: 1.0 },
  { name: "Blades - windscreen wiper - front - both", frt: 0.2 },
  { name: "Sublet 6", frt: 1.0 },
  { name: "Valves - brake bleeder - front - both - renew", frt: 1.0 },
  { name: "Sublet 3", frt: 1.0 },
  { name: "Accessory Fitment", frt: 1.0 },
  { name: "Battery Replacement -Vehicle", frt: 0.2 },
  { name: "Headlamp assemblies - both - renew", frt: 0.8 },
  { name: "Sublet 5", frt: 0.5 },
  { name: "One side Pickup or drop 3", frt: 1.5 },
  { name: "Sublet 2", frt: 1.0 },
  { name: "Tyre pressure sensors - set - renew", frt: 1.8 },
  { name: "Sublet 3", frt: 0.3 },
  { name: "Wuerth MG Special Combo 2 - Mechanical Care", frt: 0.3 },
  { name: "Sublet 4", frt: 1.0 },
];
